# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Produce verbose output by default.
VERBOSE = 1

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/sd903151/Workspace/authReq

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/sd903151/workspace/authReq

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/sd903151/workspace/authReq/CMakeFiles /Users/sd903151/workspace/authReq//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/sd903151/workspace/authReq/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named openssl

# Build rule for target.
openssl: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 openssl
.PHONY : openssl

# fast build rule for target.
openssl/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openssl.dir/build.make CMakeFiles/openssl.dir/build
.PHONY : openssl/fast

#=============================================================================
# Target rules for targets named cms_sign_verify

# Build rule for target.
cms_sign_verify: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cms_sign_verify
.PHONY : cms_sign_verify

# fast build rule for target.
cms_sign_verify/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cms_sign_verify.dir/build.make CMakeFiles/cms_sign_verify.dir/build
.PHONY : cms_sign_verify/fast

#=============================================================================
# Target rules for targets named validate_openssl

# Build rule for target.
validate_openssl: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 validate_openssl
.PHONY : validate_openssl

# fast build rule for target.
validate_openssl/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/validate_openssl.dir/build.make CMakeFiles/validate_openssl.dir/build
.PHONY : validate_openssl/fast

cms_sign_verify.o: cms_sign_verify.c.o
.PHONY : cms_sign_verify.o

# target to build an object file
cms_sign_verify.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cms_sign_verify.dir/build.make CMakeFiles/cms_sign_verify.dir/cms_sign_verify.c.o
.PHONY : cms_sign_verify.c.o

cms_sign_verify.i: cms_sign_verify.c.i
.PHONY : cms_sign_verify.i

# target to preprocess a source file
cms_sign_verify.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cms_sign_verify.dir/build.make CMakeFiles/cms_sign_verify.dir/cms_sign_verify.c.i
.PHONY : cms_sign_verify.c.i

cms_sign_verify.s: cms_sign_verify.c.s
.PHONY : cms_sign_verify.s

# target to generate assembly for a file
cms_sign_verify.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cms_sign_verify.dir/build.make CMakeFiles/cms_sign_verify.dir/cms_sign_verify.c.s
.PHONY : cms_sign_verify.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... openssl"
	@echo "... validate_openssl"
	@echo "... cms_sign_verify"
	@echo "... cms_sign_verify.o"
	@echo "... cms_sign_verify.i"
	@echo "... cms_sign_verify.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

